{"name": "test_login_page", "status": "failed", "statusDetails": {"message": "AssertionError: The user is not logged in successfully.\nassert None\n +  where None = user_is_logged()\n +    where user_is_logged = <pages.actions.login_actions.LoginActions object at 0x0000025B756B8D40>.user_is_logged", "trace": "venv\\Lib\\site-packages\\_pytest\\fixtures.py:898: in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\nfeatures\\steps\\test_login.py:31: in step_login_user_successfully\n    assert login_page.user_is_logged(), \"The user is not logged in successfully.\"\nE   AssertionError: The user is not logged in successfully.\nE   assert None\nE    +  where None = user_is_logged()\nE    +    where user_is_logged = <pages.actions.login_actions.LoginActions object at 0x0000025B756B8D40>.user_is_logged"}, "description": "login.feature: Login User", "start": 1729968354341, "stop": 1729968360107, "uuid": "70551b2f-6a03-4e7f-8888-955d47e899dc", "historyId": "433c93b71e7cd749b8bf2a660bfa517d", "testCaseId": "433c93b71e7cd749b8bf2a660bfa517d", "fullName": "features.steps.test_login#test_login_page", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "features.steps"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "manuel"}, {"name": "thread", "value": "1868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "features.steps.test_login"}]}